# Server -> Client
ROOM_UPDATE = "ROOM_UPDATE"
ROOM_SETTINGS_UPDATE = "ROOM_SETTINGS_UPDATE"
SERVER_OVERLOAD = "SERVER_OVERLOAD"

GAME_START = "GAME_START"
ROLE_ASSIGNED = "ROLE_ASSIGNED"
WOLF_SEATS = "WOLF_SEATS"

PHASE_CHANGE = "PHASE_CHANGE"
NIGHT_ACTION_REQUEST = "NIGHT_ACTION_REQUEST"
NIGHT_INFO_RESULT = "NIGHT_INFO_RESULT"

PLAYER_SPEAK = "PLAYER_SPEAK"
DEAD_CHAT = "DEAD_CHAT"

VOTE_UPDATE = "VOTE_UPDATE"
SKIP_VOTE_UPDATE = "SKIP_VOTE_UPDATE"

PHASE_RESULT = "PHASE_RESULT"
GAME_END = "GAME_END"

PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED"
PLAYER_RECONNECTED = "PLAYER_RECONNECTED"
HOST_TRANSFERRED = "HOST_TRANSFERRED"
RESUME_AVAILABLE = "RESUME_AVAILABLE"
GAME_STATE_SYNC = "GAME_STATE_SYNC"

# Client -> Server
READY = "READY"
UNREADY = "UNREADY"
LEAVE_ROOM = "LEAVE_ROOM"
UPDATE_ROOM_SETTINGS = "UPDATE_ROOM_SETTINGS"
START_GAME = "START_GAME"

NIGHT_ACTION = "NIGHT_ACTION"
CHANGE_NIGHT_ACTION = "CHANGE_NIGHT_ACTION"
WOLF_VOTE = "WOLF_VOTE"
CHANGE_WOLF_VOTE = "CHANGE_WOLF_VOTE"

DAY_SPEAK = "DAY_SPEAK"
SKIP_DISCUSSION = "SKIP_DISCUSSION"

VOTE = "VOTE"
CHANGE_VOTE = "CHANGE_VOTE"

RESUME_GAME = "RESUME_GAME"
